export const LOADING_ACCOUNT: string = 'LOADING_ACCOUNT'
export const SET_ACCOUNT: string = 'SET_ACCOUNT'
export const SET_ASSETS_TOKEN: string = 'SET_ASSETS_TOKEN'
export const SET_CONFIG_ASSET: string = 'SET_CONFIG_ASSET'
export const SET_CONFIG_UNIT: string = 'SET_CONFIG_UNIT'
export const SET_PUBLIC_SOCKET: string = 'SET_PUBLIC_SOCKET'
